### PR TITLE
Add controls for AILabImage component stories - Half-Fix

### LINKED ISSUE #34: Add Params to AILabImage
As of right now AILabImage is hardcoded.

Move the model and model config for SSD to params.

### PR DESCRIPTION
**Pull request by GantMan**
Adds controls to Image story - also required fixes that close #34 and tie into completing #33.
This also identified the bug #35 

image

### CODE REVIEW

File: packages/ai-lab/src/components/AILabImage/AILabImage.tsx [hunk 1]
```diff
@@ -60,29 +80,31 @@ export const AILabImage = ({
...
-    //   nmsDetections.selectedIndices,
-    //   nmsDetections.selectedScores,
-    //   prominentDetection.indices,
-    //   prominentDetection.values,
-    //   tensor,
-    //   readyfied,
-    //   justBoxes,
-    //   justValues,
-    // ]);
+    tf.dispose([
```
Comment (GantMan) [inline packages/ai-lab/src/components/AILabImage/AILabImage.tsx:93]: I'm not sure why this dispose was commented out, but it needs to be brought back in to protect from mem-leaks

Comment (kateinkim) [reply packages/ai-lab/src/components/AILabImage/AILabImage.tsx:93]: You are right! I was getting type errors and since fast refresh disposed tensors I commented those out then forgot to brought them back even after the type errors are fixed in different components.

**Review by kateinkim — APPROVED** [review]
